version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        ENVIRONMENT: test
    env_file: ./config/.env
    volumes:
      - ./negrucoin/static:/django_static
    command: python manage.py runserver
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    env_file: ./config/.env

volumes:
  postgres_data:
