version: "3"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./negrucoin/static:/django_static
      - ./docker/nginx/negru.pem:/etc/nginx/ssl/negru.pem
      - ./docker/nginx/negru.key:/etc/nginx/ssl/negru.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        ENVIRONMENT: production
    env_file: ./config/.env
    volumes:
      - ./negrucoin/static:/django_static
    expose:
      - 8000
    command: [
      "/wait-for-it.sh", "db:5432", "--strict", "--timeout=300", "--",
      "/docker/django/start_server.sh"
    ]
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./config/.env

volumes:
  postgres_data:
