# Generated by Django 4.1.1 on 2022-12-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('default', 'Пользователь'), ('manager', 'Менеджер'), ('admin', 'Админ')], default='default', max_length=255, verbose_name='Тип аккаунта')),
                ('money_profit', models.BigIntegerField(default=0, verbose_name='Профит монет')),
                ('rubles', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Кол-во рублей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_count', models.BigIntegerField(verbose_name='Кол-во монет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_money_transfers', to='main.client', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_money_transfers', to='main.client', verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='MoneySaleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('closed', 'Закрыт'), ('sold_out', 'Раскуплен')], default='created', max_length=255, verbose_name='Статус')),
                ('money', models.BigIntegerField(verbose_name='Кол-во монет в предложении')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена всего предложения (в рублях)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_sale_lots', to='main.client', verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.BigIntegerField(verbose_name='Кол-во купленных монет')),
                ('rubles', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Кол-во потраченных рублей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_money_purchases', to='main.client', verbose_name='Покупатель')),
                ('money_sale_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_purchases', to='main.moneysaleoffer', verbose_name='Предложение продажи монет')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_money_purchases', to='main.client', verbose_name='Продавец')),
            ],
        ),
    ]
