# Generated by Django 4.1.1 on 2022-12-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSING', 'В обработке'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='PROCESSING', max_length=255, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сумма (в рублях)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='main.client', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='QIWIBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Ожидается'), ('EXPIRED', 'Просрочен'), ('REJECTED', 'Отклонен'), ('PAID', 'Оплачен')], default='WAITING', max_length=255, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма (в рублях)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('expired_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qiwi_bills', to='main.client', verbose_name='Кому выставлен')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payment.withdrawalrequest', verbose_name='Запрос на вывод средств')),
            ],
        ),
    ]
