name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - run: cp config/.env.template config/.env
    - run: docker-compose -f docker-compose.ci.yml run web sh /docker/ci.sh
    - run: docker-compose -f docker-compose.ci.yml down --volumes
